"""Summarise the v1-vs-v2 exploration (validation seeds only).

Writes docs/EXPLORATION_V2.md entirely from data/results/exploration_v2_validation.csv,
so no number in it is typed. Everything here is exploratory: validation seeds, no
pre-declared hypotheses, and p-values that are descriptive rather than evidence.

    python scripts/analyze_exploration.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from exonaut.environments import TRUE_CLASS_PARAMS, TerrainClass
from exonaut.experiments.analysis import interval_table, paired_binary, paired_continuous

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "results" / "exploration_v2_validation.csv"
OUT_MD = ROOT / "docs" / "EXPLORATION_V2.md"
OUT_JSON = ROOT / "data" / "results" / "exploration_v2_summary.json"
ORDER = ["moon_id", "mars_ood", "mars_high_uncertainty", "mars_faults", "mars_comm_delay"]
PLANNERS = ["astar", "risk_aware_astar", "adaptive_risk_aware_astar"]
SHORT = {
    "astar": "distance-only",
    "risk_aware_astar": "fixed",
    "adaptive_risk_aware_astar": "adaptive",
}


def calibration(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    ad = df[df.planner == "adaptive_risk_aware_astar"]
    for _, r in ad.iterrows():
        truth = TRUE_CLASS_PARAMS[r["body"]]
        for k in range(5):
            n = r.get(f"belief_n_class{k}", 0)
            if not n or n < 1:
                continue
            mean, sd = r[f"belief_class{k}"], r[f"belief_sd_class{k}"]
            t = truth[TerrainClass(k)].slip_mean
            rows.append(
                {
                    "engine": r["engine"],
                    "condition": r["condition"],
                    "cls": k,
                    "covered": abs(mean - t) <= 1.96 * sd,
                    "abs_error": abs(mean - t),
                }
            )
    return pd.DataFrame(rows)


def main() -> None:
    df = pd.read_csv(DATA)
    df["science_fraction"] = df.science_return / df.science_possible
    out: dict = {
        "n_missions": int(len(df)),
        "seeds": sorted(df.seed.unique().tolist())[:1] + sorted(df.seed.unique().tolist())[-1:],
        "engines": {},
    }
    lines = [
        "# Exploration: engine v1 vs v2 (validation seeds)",
        "",
        "> **Exploratory, not confirmatory.** Auto-generated by `scripts/analyze_exploration.py`",
        "> from `data/results/exploration_v2_validation.csv`. Validation seeds only; no hypotheses",
        "> were declared in advance, so p-values below are descriptive, not evidence.",
        "",
        f"{len(df)} missions: 2 engines x {df.condition.nunique()} conditions x 3 planners x "
        f"{df.seed.nunique()} validation seeds ({df.seed.min()}-{df.seed.max()}), confirmatory mission size.",
        "",
    ]

    # 1. do the fixes do what they claim?
    lines += ["## 1. Do the fixes do what they claim?", ""]
    f = df[df.condition == "mars_faults"].assign(any_fault=lambda d: d.faults_fired > 0)
    fired = f.groupby("engine")["any_fault"].mean()
    tout = df[df.termination == "timeout"]
    at_lander = tout.assign(home=tout.final_distance_from_home == 0).groupby("engine")["home"].sum()
    n_tout = tout.groupby("engine").size()
    interv = df[df.body == "mars"].groupby("engine")["interventions"].median()
    lander_timeouts = tout[tout.final_distance_from_home == 0]
    lander_help = lander_timeouts.groupby("engine")["interventions"].median()
    cal = calibration(df)
    cov = cal.groupby("engine")["covered"].mean()
    err = cal.groupby("engine")["abs_error"].median()
    lines += [
        "| check | v1 | v2 |",
        "|---|---|---|",
        f"| fault condition: missions where a fault fired | {fired.get('v1', 0):.0%} | {fired.get('v2', 0):.0%} |",
        f"| timeouts (all conditions) | {n_tout.get('v1', 0)} | {n_tout.get('v2', 0)} |",
        f"| ...of which parked at the lander | {int(at_lander.get('v1', 0))} | {int(at_lander.get('v2', 0))} |",
        f"| ...median help requests in those lander timeouts | {lander_help.get('v1', 0):.0f} | {lander_help.get('v2', 0):.0f} |",
        f"| median ground interventions per Mars mission | {interv.get('v1', 0):.0f} | {interv.get('v2', 0):.0f} |",
        f"| adaptive learner: 95% interval coverage of class-mean slip | {cov.get('v1', 0):.2f} | {cov.get('v2', 0):.2f} |",
        f"| adaptive learner: median abs. error in class-mean slip | {err.get('v1', 0):.3f} | {err.get('v2', 0):.3f} |",
        "",
        "A calibrated learner would cover the truth about 95% of the time. v2 lander timeouts",
        "are rovers waiting at the lander to recharge, not requesting help: the livelock is gone,",
        "but a slow recharge can still run out the step budget.",
        "",
    ]
    # conditions that became identical under an engine are flagged automatically
    notes = []
    key_cols = ["termination", "science_return", "energy_spent", "steps"]
    for engine in ("v1", "v2"):
        sub = df[df.engine == engine]
        base = sub[sub.condition == "mars_ood"].set_index(["planner", "seed"]).sort_index()
        for c in ORDER:
            if c in ("mars_ood", "moon_id"):
                continue
            other = sub[sub.condition == c].set_index(["planner", "seed"]).sort_index()
            if len(other) == len(base) and (other[key_cols] == base[key_cols]).all(axis=1).all():
                notes.append((engine, c))
    if notes:
        lines += [
            "**Degenerate conditions.** Under the engine shown, these conditions produced "
            "missions identical to plain Mars OOD, so they measure nothing extra:",
            "",
        ]
        for engine, c in notes:
            lines.append(f"- {engine}: `{c}`")
        lines += [
            "",
            "Communication delay only costs time when the rover requests help. v2 removes "
            "the ratchet and the livelock, the rover almost never asks, and with independent "
            "random streams nothing else differs. A v2 study would need a condition where "
            "delay actually binds.",
            "",
        ]
    out["degenerate_conditions"] = notes
    out["checks"] = {
        "fault_fired": fired.to_dict(),
        "timeouts": n_tout.to_dict(),
        "timeouts_at_lander": at_lander.astype(int).to_dict(),
        "median_interventions_mars": interv.to_dict(),
        "coverage": cov.to_dict(),
        "median_abs_error": err.to_dict(),
    }

    # 2. outcomes
    lines += [
        "## 2. Outcomes by engine",
        "",
        "Success with Wilson 95% interval; science fraction with t interval.",
        "",
    ]
    for engine in ("v1", "v2"):
        sub = df[df.engine == engine]
        iv = interval_table(sub)
        lines += [
            f"### {engine}",
            "",
            "| condition | planner | success [95%] | science [95%] |",
            "|---|---|---|---|",
        ]
        for c in ORDER:
            for p in PLANNERS:
                r = iv[(iv.condition == c) & (iv.planner == p)]
                if r.empty:
                    continue
                r = r.iloc[0]
                lines.append(
                    f"| {c} | {SHORT[p]} | {r.success_rate:.2f} [{r.success_ci_low:.2f}, {r.success_ci_high:.2f}] "
                    f"| {r.science_fraction:.3f} [{r.science_ci_low:.3f}, {r.science_ci_high:.3f}] |"
                )
        lines.append("")
        out["engines"][engine] = iv.to_dict(orient="records")

    # 3. paired adaptive vs fixed
    lines += [
        "## 3. Adaptive minus fixed, paired by seed (descriptive)",
        "",
        "| engine | condition | success diff [95% CI] | McNemar p | science diff [95% CI] | paired-t p |",
        "|---|---|---|---|---|---|",
    ]
    contrasts = []
    for engine in ("v1", "v2"):
        sub = df[df.engine == engine]
        for c in ORDER:
            b = paired_binary(sub, "adaptive_risk_aware_astar", "risk_aware_astar", c)
            s = paired_continuous(
                sub, "science_fraction", "adaptive_risk_aware_astar", "risk_aware_astar", c
            )
            if not b or not s:
                continue
            contrasts.append({"engine": engine, "condition": c, "success": b, "science": s})
            lines.append(
                f"| {engine} | {c} | {b['mean_diff']:+.3f} [{b['ci95_low']:+.3f}, {b['ci95_high']:+.3f}] | "
                f"{b['p_value']:.3f} | {s['mean_diff']:+.3f} [{s['ci95_low']:+.3f}, {s['ci95_high']:+.3f}] | {s['p_value']:.3f} |"
            )
    lines += [
        "",
        "Uncorrected, exploratory p-values across 20 contrasts: roughly one would fall below "
        "0.05 by chance alone even if nothing were going on.",
        "",
    ]
    out["contrasts"] = contrasts

    # 4. planning note for any future v2 study
    lines += [
        "## 4. Planning note: how many seeds would a v2 study need?",
        "",
        "For each Martian condition, the number of matched seeds needed for the 95% interval "
        "on the adaptive-minus-fixed success difference to have a half-width of 0.05, using "
        "the spread of paired differences observed here under v2 (normal approximation).",
        "",
        "| condition | observed v2 diff | sd of paired diffs | seeds needed |",
        "|---|---|---|---|",
    ]
    planning = {}
    v2 = df[df.engine == "v2"]
    for c in ORDER:
        if c == "moon_id" or ("v2", c) in notes:
            continue
        w = v2[v2.condition == c].pivot_table(index="seed", columns="planner", values="success")
        d = w["adaptive_risk_aware_astar"].astype(float) - w["risk_aware_astar"].astype(float)
        sd = float(d.std(ddof=1))
        needed = int(np.ceil((1.96 * sd / 0.05) ** 2)) if sd > 0 else 0
        planning[c] = {"diff": float(d.mean()), "sd": sd, "seeds_needed": needed}
        lines.append(f"| {c} | {d.mean():+.3f} | {sd:.3f} | {needed} |")
    lines += [
        "",
        "The v1 confirmatory study used 50 seeds per condition. The test and OOD splits hold "
        "496 usable seeds each, 446 of them not yet used.",
        "",
    ]
    out["planning"] = planning

    OUT_MD.write_text("\n".join(lines) + "\n")
    OUT_JSON.write_text(
        json.dumps(out, indent=2, default=lambda o: o.item() if hasattr(o, "item") else str(o))
    )
    print("\n".join(lines))


if __name__ == "__main__":
    main()
