"""Does Study 1's conclusion depend on the platform it is re-run on?

Study 1 was generated on macOS arm64. The GitHub workflow
"v1 reproduction (Linux)" re-ran all 750 missions on Linux x86-64 with the
same code and pinned libraries; its outcomes are in
data/results/cross_platform/. This recomputes the pre-specified primary
analysis on the Linux outcomes and writes a side-by-side comparison. It is a
robustness check on Study 1, not a replacement for it.

    python scripts/cross_platform_check.py
"""

import json
from pathlib import Path

import pandas as pd

from exonaut.experiments.analysis import primary_analysis

ROOT = Path(__file__).resolve().parents[1]
DIR = ROOT / "data" / "results" / "cross_platform"


def main() -> None:
    committed = pd.read_csv(ROOT / "data/results/exonaut_main.csv")
    linux = pd.read_csv(DIR / "linux_x86_64_rows.csv")
    keys = ["condition", "planner", "seed"]
    merged = committed.merge(linux, on=keys, suffixes=("", "_linux"))
    assert len(merged) == len(committed) == 750
    differs = (
        (merged.termination != merged.termination_linux)
        | ((merged.science_return - merged.science_return_linux).abs() > 1e-9)
        | ((merged.energy_spent - merged.energy_spent_linux).abs() > 1e-6)
    )
    outcome_changed = merged.success.astype(bool) != merged.success_linux.astype(bool)

    rerun = committed.copy()
    lx = linux.set_index(keys)
    for col in ("termination", "success", "science_return", "energy_spent", "steps"):
        rerun[col] = [lx.loc[tuple(k), col] for k in committed[keys].itertuples(index=False)]
    a = primary_analysis(committed).set_index(["condition", "metric"])
    b = primary_analysis(rerun).set_index(["condition", "metric"])
    rows = []
    for idx in a.index:
        rows.append(
            {
                "condition": idx[0],
                "metric": idx[1],
                "diff_macos": float(a.loc[idx, "mean_diff"]),
                "diff_linux": float(b.loc[idx, "mean_diff"]),
                "p_holm_macos": float(a.loc[idx, "p_holm"]),
                "p_holm_linux": float(b.loc[idx, "p_holm"]),
                "significant_macos": bool(a.loc[idx, "significant"]),
                "significant_linux": bool(b.loc[idx, "significant"]),
            }
        )
    table = pd.DataFrame(rows)
    table.to_csv(DIR / "primary_comparison.csv", index=False)
    summary = {
        "missions": 750,
        "bit_identical": int((~differs).sum()),
        "differ": int(differs.sum()),
        "differ_by_condition": merged[differs].groupby("condition").size().to_dict(),
        "differ_by_planner": merged[differs].groupby("planner").size().to_dict(),
        "success_flipped": int(outcome_changed.sum()),
        "same_significance_verdicts": bool(
            (table.significant_macos == table.significant_linux).all()
        ),
        "significant_macos": table[table.significant_macos][["condition", "metric"]].to_dict(
            "records"
        ),
        "significant_linux": table[table.significant_linux][["condition", "metric"]].to_dict(
            "records"
        ),
    }
    (DIR / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    ff = table[(table.condition == "mars_faults") & (table.metric == "success")].iloc[0]
    macros = [
        "% AUTO-GENERATED by scripts/cross_platform_check.py (Linux re-run of Study 1).",
        rf"\newcommand{{\XpIdentical}}{{{summary['bit_identical']}}}",
        rf"\newcommand{{\XpDiffer}}{{{summary['differ']}}}",
        rf"\newcommand{{\XpFlipped}}{{{summary['success_flipped']}}}",
        rf"\newcommand{{\XpMaxShift}}{{{(table.diff_macos - table.diff_linux).abs().max():.3f}}}",
        rf"\newcommand{{\XpSameVerdicts}}{{{'yes' if summary['same_significance_verdicts'] else 'no'}}}",
        rf"\newcommand{{\XpFaultsDiffLinux}}{{{ff.diff_linux:.2f}}}",
        rf"\newcommand{{\XpFaultsPLinux}}{{{ff.p_holm_linux:.3f}}}",
    ]
    (ROOT / "paper/tables/exonaut_crossplatform_macros.tex").write_text("\n".join(macros) + "\n")
    print(json.dumps(summary, indent=2))
    print(table.round(3).to_string(index=False))


if __name__ == "__main__":
    main()
