"""Generate the EXONAUT paper's pilot tables, macros, and figures.

All reported pilot values are derived from the committed row-level CSV. The
script intentionally labels them as pilot results and does not perform a
confirmatory hypothesis test on four seeds per condition.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TABLE_DIR = PROJECT_ROOT / "paper" / "tables"
FIGURE_DIR = PROJECT_ROOT / "paper" / "figures"

PLANNER_LABELS = {
    "astar": "Distance-only A*",
    "risk_aware_astar": "Fixed risk-aware A*",
    "adaptive_risk_aware_astar": "Adaptive risk-aware A*",
}

CONDITION_LABELS = {
    "moon_id": "Moon (in distribution)",
    "mars_ood": "Mars (OOD)",
    "mars_high_uncertainty": "Mars (1.5x slip dispersion)",
    "mars_faults": "Mars (fault injection)",
    "mars_comm_delay": "Mars (20-step intervention delay)",
}

COLORS = {
    "astar": "#777777",
    "risk_aware_astar": "#2f6f9f",
    "adaptive_risk_aware_astar": "#c94c4c",
}


def _latex_escape(text: str) -> str:
    return text.replace("&", r"\&").replace("%", r"\%")


def _macro(name: str, value) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def generate(csv_path: Path) -> None:
    df = pd.read_csv(csv_path)
    required = {
        "condition", "planner", "seed", "success", "science_return",
        "science_possible", "energy_spent", "interventions",
    }
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"missing required columns: {sorted(missing)}")
    if (df["science_possible"] <= 0).any():
        raise ValueError("science_possible must be positive")

    df = df.copy()
    df["science_fraction"] = df["science_return"] / df["science_possible"]
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)

    macros = [
        "% AUTO-GENERATED by scripts/make_exonaut_paper_assets.py",
        _macro("PilotMissions", len(df)),
        _macro(
            "PilotSeedsPerCondition",
            int(df.groupby("condition")["seed"].nunique().min()),
        ),
        _macro("PilotConditions", df["condition"].nunique()),
        _macro("PilotPlanners", df["planner"].nunique()),
    ]
    mars = df[df["body"] == "mars"]
    for planner, prefix in [
        ("astar", "PilotAstar"),
        ("risk_aware_astar", "PilotFixed"),
        ("adaptive_risk_aware_astar", "PilotAdaptive"),
    ]:
        group = mars[mars["planner"] == planner]
        macros.extend([
            _macro(prefix + "Science", f"{group['science_fraction'].mean():.3f}"),
            _macro(prefix + "Success", f"{100 * group['success'].mean():.0f}\\%"),
        ])
    (TABLE_DIR / "exonaut_macros.tex").write_text("\n".join(macros) + "\n")

    summary = (
        df.groupby(["condition", "planner"], as_index=False)
        .agg(
            science_fraction=("science_fraction", "mean"),
            success_rate=("success", "mean"),
            energy=("energy_spent", "mean"),
            interventions=("interventions", "mean"),
        )
    )
    lines = [
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Pilot outcomes. Values are descriptive means over four matched reserved seeds per condition; they are not confirmatory estimates.}",
        r"\label{tab:pilot}",
        r"\small",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Condition & Planner & Science fraction & Safe return & Energy spent & Interventions \\",
        r"\midrule",
    ]
    for condition in CONDITION_LABELS:
        block = summary[summary["condition"] == condition]
        first = True
        for planner in ("astar", "risk_aware_astar", "adaptive_risk_aware_astar"):
            row = block[block["planner"] == planner].iloc[0]
            condition_text = _latex_escape(CONDITION_LABELS[condition]) if first else ""
            lines.append(
                f"{condition_text} & {_latex_escape(PLANNER_LABELS[planner])} & "
                f"{row.science_fraction:.3f} & {100 * row.success_rate:.0f}\\% & "
                f"{row.energy:.1f} & {row.interventions:.1f} \\\\"
            )
            first = False
        lines.append(r"\addlinespace")
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ])
    (TABLE_DIR / "exonaut_pilot_summary.tex").write_text("\n".join(lines) + "\n")

    condition_order = list(CONDITION_LABELS)
    planner_order = ["astar", "risk_aware_astar", "adaptive_risk_aware_astar"]
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.1), constrained_layout=True)
    x = list(range(len(condition_order)))
    width = 0.24
    for index, planner in enumerate(planner_order):
        block = summary[summary["planner"] == planner].set_index("condition")
        offset = (index - 1) * width
        axes[0].bar(
            [value + offset for value in x],
            [block.loc[c, "science_fraction"] for c in condition_order],
            width=width,
            label=PLANNER_LABELS[planner],
            color=COLORS[planner],
        )
        axes[1].bar(
            [value + offset for value in x],
            [block.loc[c, "success_rate"] for c in condition_order],
            width=width,
            color=COLORS[planner],
        )
    short_labels = ["Moon ID", "Mars OOD", "Mars +uncert.", "Mars +faults", "Mars +delay"]
    for ax in axes:
        ax.set_xticks(x, short_labels, rotation=25, ha="right")
        ax.set_ylim(0, 1.05)
        ax.grid(axis="y", alpha=0.25)
        ax.spines[["top", "right"]].set_visible(False)
    axes[0].set_ylabel("Mean science value collected / possible")
    axes[0].set_title("Science return")
    axes[1].set_ylabel("Fraction returning safely")
    axes[1].set_title("Mission success")
    fig.legend(*axes[0].get_legend_handles_labels(), loc="outside lower center", ncol=3,
               frameon=False)
    fig.savefig(FIGURE_DIR / "exonaut_pilot_outcomes.pdf", bbox_inches="tight")
    fig.savefig(FIGURE_DIR / "exonaut_pilot_outcomes.png", dpi=220, bbox_inches="tight")
    plt.close(fig)

    print(f"generated EXONAUT paper assets from {csv_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input", type=Path,
        default=PROJECT_ROOT / "data" / "results" / "exonaut_pilot.csv",
    )
    args = parser.parse_args()
    generate(args.input)


if __name__ == "__main__":
    main()
